[package]
name = "joystick-dvip-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.10.4"
hex = "0.4.3"
pasts = "0.14.3"
stick = "0.13.0"
